### PR TITLE
remove_version feature

### PR DESCRIPTION
**Pull request by mjhajharia**
As per #10

### CODE REVIEW

**Comment by mjhajharia** [comment]
@SpacemanPaul this is how it would look

`shell`
image

`sphinx`

https://deprecat--11.org.readthedocs.build/en/11/source/api.html#deprecat.example.test_deprecat_on_class_method

let me know what do you think

**Comment by SpacemanPaul** [comment]
> @SpacemanPaul this is how it would look

Yes exactly!  Thanks so much!

**Comment by SpacemanPaul** [comment]
Hi Meenal.  Any idea when this will be merged/released?

**Comment by mjhajharia** [comment]
Hi, apologies for the delay, I'll make a release this week!

**Comment by SpacemanPaul** [comment]
> Hi, apologies for the delay, I'll make a release this week!

Any update on this?  Or is this fork dead in the water now `deprecated` is starting to push our releases again?  (If so, it might be nice to push one last release stating that `deprecat` is depreacted in favour of `deprecated`.  :) )

**Comment by mjhajharia** [comment]
done! will fix the sphinx string tests later, it's mostly minor bugs, as the examples.py api example works https://deprecat.readthedocs.io/en/latest/source/api.html#examples

**Comment by SpacemanPaul** [comment]
Thanks Meenal - I really appreciate it.

**Comment by SpacemanPaul** [comment]
The new release hasn't been pushed to PyPI.

**Pull request merged**
